project:
  type: website
  output-dir: docs

website:
  # google-analytics: "G-9QW2N0QB7G"
  title: "Entomology 5126"
  favicon: media/web-favicon.png
  navbar:
    logo: media/5126-sticker.png
    title: false
    left:
      - href: index.qmd
        text: Home
      - syllabus.qmd
      - schedule.qmd
      - href: content/index.qmd
        text: Content
      - href: lab/index.qmd
        text: Labs
      - resources.qmd
    right:
      - href: media/ent5126-syllabus_sp2026.pdf # providing a relative file path to a pdf will open up a browser-based pdf viewer when clicked
        text: Course Syllabus
        icon: file-pdf
        target: _blank # opens link (or page) in a new browser tab
      - icon: github # add icons as navbar buttons
        href: https://github.com/jhemberger/entomology-5126
        target: _blank
      - icon: envelope
        href: mailto:jhemberg@umn.edu
  page-footer:
    background: light # or `dark`
    left: Copyright 2025, Jeremy Hemberger
    # center: |
    #   Background image: Large milkweed bug nymph aggregation (<i>Oncopeltus fasciatus</i>), 2017
    right: Built with [{{< fa brands r-project title="R Project" >}}](https://www.r-project.org/about.html){target=_blank} and [Quarto](https://quarto.org/){target=_blank}
  sidebar:
    - title: "Labs"
      style: "docked"
      search: false
      background: light
      contents: 
        - section: "Getting started"
          contents:
            - lab/index.qmd
        - section: "Module 1: RStudio and Tidyverse crash course"
          contents:
            - text: "Lab 1: An introduction to R"
              file: lab/w1-lab.qmd
            - text: "Lab 2: Data wrangling and plotting"
              file: lab/w2-lab.qmd
            - text: "Lab 3: Summarizing data"
              file: lab/w3-lab.qmd
        - section: "Module 2: Reviewing foundations in statistics"
          contents:
            - text: "Lab 4: Independent two-sample t-tests and ANOVA"
              file: lab/w4-lab.qmd
            - text: "Lab 5: Simple linear regression"
              file: lab/w5-lab.qmd
            - text: "Lab 6: Multiple linear regression and ANCOVA"
              file: lab/w6-lab.qmd
            - text: "Lab 7: Curvy data"
              file: lab/w7-lab.qmd
        - section: "Module 3: Integrating time into our models"
          contents:
            - text: "Lab 8: Time series: Autoregressive models"
              file: lab/w8-lab.qmd
            - text: "Lab 9: Mixed-effects models for time series"
              file: lab/w9-lab.qmd
        - section: "Module 4: Integrating space into our models"
          contents:
            - text: "Lab 10: Spatial point processes: Ripley’s K"
              file: lab/w10-lab.qmd
            - text: "Lab 11: Spatial point process models"
              file: lab/w11-lab.qmd
            - text: "Lab 12: Lattice data: Spatial linear models"
              file: lab/w12-lab.qmd
            - text: "Lab 13: Geostatistics"
              file: lab/w13-lab.qmd
    - title: "Content"
      style: "docked"
      search: false
      background: light
      contents: 
        - section: "Overview"
          contents:
            - content/index.qmd
        - section: "Module 1: RStudio and Tidyverse crash course"
          contents:
            - text: "Week 1: Class orientation and introduction to R and data wrangling"
              file: content/w1-content.qmd
        - section: "Module 2: Reviewing foundations in statistics"
          contents:
            - text: "Week 2: Sampling, probability, random variables"
              file: content/w2-content.qmd
            - text: "Week 3: Data transformations, hypotheses, t-tests"
              file: content/w3-content.qmd
            - text: "Week 4: More t-tests and ANOVA"
              file: content/w4-content.qmd
            - text: "Week 5: Correlation and simple linear regression"
              file: content/w5-content.qmd
            - text: "Week 6: Multiple regression"
              file: content/w6-content.qmd
            - text: "Week 7: Model selection and midterm review"
              file: content/w7-content.qmd
        - section: "Module 3: Integrating time into our models"
          contents:
            - text: "Week 9: Midterm review and introduction to space and time"
              file: content/w9-content.qmd
            - text: "Week 10: Mixed effects models, information critera"
              file: content/w10-content.qmd
        - section: "Module 4: Integrating space into our models"
          contents:
            - text: "Week 11: Spatial point processes, generalized linear models"
              file: content/w11-content.qmd
            - text: "Week 12: More GLMs and point process models"
              file: content/w12-content.qmd
            - text: "Week 13: Lattice data, autocorrelation, SAR/CAR models"
              file: content/w13-content.qmd
            - text: "Week 14: Geostatistics"
              file: content/w14-content.qmd
            - text: "Week 15: Course wrap-up and final exam review"
              file: content/w15-content.qmd


format:
  html:
    theme: 
      - styles.scss
    # css: styles.scss
    toc: true
    mainfont: Roboto Condensed
    page-layout: full
    highlight-style: ayu

editor: visual

  