---
title: "Overview of labs + basic info"
sidebar: true
toc: true
page-layout: full
---

------------------------------------------------------------------------

Here, you'll find the virtual companion to all of our hands-on labs for the semester. These will be the same as your physical hand-outs, but I know many folks prefer to have them up on their screens as they work through the activities.

The purpose of these labs is to practice applying the topics that we discuss in lecture using real-world examples and data. The associated data files for each lab are linked in the `Frontmatter` section atop each page (all the files are also located [here](link%20here)). Over the semester, we'll explore some of the frustrations and challenges of working with bio/ecological data (of which there are many!), but together we'll conquer them, setting y'all up for success in analyzing, interpreting, and sharing your own data.

As a reminder, each of the 13 labs will have an assignment/report that will be evaluated. The first three periods will be devoted to a primer of using R/RStudio for managing, wrangling, and interpreting data, and the reports associated with these will receive feedback but will not be included in the course grade. The remaining 10 lab assignments/reports will be graded and count toward 40% of total course grade (4% per report). There will also be a lab final worth 15% of the total course grade. In this, students will be given a real data set to analyze and develop a report for during the last lab period.

## Downloading, installing, and setting up R and RStudio

For this course, we'll be using the Posit Cloud service for labs and assignments. It's essentially an online virtual machine to run RStudio in your browser. This will avoid version issues, package incompatibilities, and Mac vs Windows challenges that we might otherwise face. This is a paid service we'll be using for class and it will expire after our semester concludes, so I also encourage you to install R and R Studio on your own machines if you haven't already. Click on the buttons below to install both R (the language, or engine that enables our analyses to be performed) and RStudio (the shell, or vessel that the engine of R sits in and gives us the nifty features to manage files, version history, and write pretty and readable code).

<p class="buttons" style="text-align:left;">

[{{< fa cloud >}} [Launch Posit Cloud](https://posit.cloud/)]{.btn .btn-outline-warning} [{{< fa brands r-project title="R Project">}} [Download R](https://cran.r-project.org/)]{.btn .btn-outline-warning} [{{< fa registered >}} [Download RStudio](https://posit.co/download/rstudio-desktop/)]{.btn .btn-outline-warning}

</p>

### Quality of life improvements

RStudio is a highly customizable program that will let you nerd out to your heart's content. Feel free! A few things that I suggest you customize right away will help you (and me) to debug and read your code.

-   After launching RStudio, go to Tools ---\> Global options.
-   Select the "Appearance" tab on the side, and select an editor theme that you like best. I highly recommend one where comments (text preceded by a #) are some shade of gray. This helps them be obvious without being obnoxiously bright and distracting.
-   Next, select the "Code" tab on the side, and then select the "Display" panel. Enable: `Highlight selected line`, `Allow scroll past end of document`, `Highlight function calls`, and `Use rainbow parentheses` 🌈. These things will help you better catch syntax errors with missed parentheses, and help you and me quickly see where you're editing in your R files.

## Completing and submitting labs

In labs, we'll be writing code in a couple of different ways, but primarily what I will be recommending is using an R Notebook to write, annotate, and interpret your code. R Notebooks are a type of Markdown file where we can mix formatted text, code chunks, and a whole bunch of other goodies. R Notebooks help to organize your code into sections and subsections, and will let you write about the output directly in the document rather than creating a Word document (shudder...). We'll go through this a bit more in the first lab, but take a look at the following links to learn a bit more about R Notebooks and R Markdown.

-   [Writing code in R notebooks](https://bookdown.org/yihui/rmarkdown/notebook.html)
-   [R Notebook (Markdown) cheatsheet](https://posit.co/wp-content/uploads/2022/10/rmarkdown-1.pdf)